### ISSUE TITLE
최종 발표

### ISSUE THREAD

**Issue by taeyang1224** [taeyang1224/Final_Project#33]
- [x] PPT 만들기
- [x] 노션 정리
- [x] Github 정리
- [x] 코드 정리

**Comment by dongyoung0** [comment]
결과창 캡쳐하기

**Comment by dongyoung0** [comment]
LGB - feature importance 확인
DeepFM - Loss 시각화, Activation Function, Prediction Layer 언급?
- Config 파일 만들기?
